import React, { useState } from "react";
import axios from "axios";
import { API_ENDPOINTS } from "../config/api";

const TeacherSignup = ({ onSignupSuccess }) => {
  const [formData, setFormData] = useState({
    teacherName: "",
    teacherId: "", // Will be generated by backend
  });

  const [errors, setErrors] = useState({});
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [message, setMessage] = useState({ type: "", text: "" });

  // Handle input changes
  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData((prev) => ({
      ...prev,
      [name]: value,
    }));
    // Clear error for this field when user starts typing
    if (errors[name]) {
      setErrors((prev) => ({
        ...prev,
        [name]: "",
      }));
    }
  };

  // Basic form validation
  const validateForm = () => {
    const newErrors = {};

    if (!formData.teacherName.trim()) {
      newErrors.teacherName = "Teacher name is required";
    } else if (formData.teacherName.trim().length < 2) {
      newErrors.teacherName = "Name must be at least 2 characters";
    }

    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  // Handle form submission
  const handleSubmit = async (e) => {
    e.preventDefault();
    setMessage({ type: "", text: "" });

    if (!validateForm()) {
      return;
    }

    setIsSubmitting(true);

    try {
      // Backend API endpoint: POST /faculty
      // Request body: { "name": "string" }
      const response = await axios.post(API_ENDPOINTS.FACULTY_REGISTER, {
        name: formData.teacherName.trim(),
      });

      // Backend response format: { success: true/false, message: "...", data: { id, name, ... } }
      if (response.data && response.data.success && response.data.data) {
        const facultyId = response.data.data.id;
        
        // Store teacher ID and name in localStorage
        localStorage.setItem("teacherId", facultyId.toString());
        localStorage.setItem("teacherName", response.data.data.name || formData.teacherName);
        
        setMessage({
          type: "success",
          text: "Registration successful! Redirecting to dashboard...",
        });

        // Redirect to dashboard after successful registration
        setTimeout(() => {
          if (onSignupSuccess) {
            onSignupSuccess(facultyId.toString());
          }
        }, 1500);
      } else {
        setMessage({
          type: "error",
          text: response.data?.message || "Registration failed. Please try again.",
        });
      }
    } catch (error) {
      console.error("Registration error:", error);
      setMessage({
        type: "error",
        text:
          error.response?.data?.message ||
          error.response?.data?.error ||
          "Registration failed. Please check your connection and try again.",
      });
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <div className="signup-container">
      <div className="signup-card">
        <h2>Teacher Registration</h2>
        <p className="subtitle">Create your account to get started</p>

        <form onSubmit={handleSubmit} className="signup-form">
          <div className="form-group">
            <label htmlFor="teacherName">Teacher Name *</label>
            <input
              type="text"
              id="teacherName"
              name="teacherName"
              value={formData.teacherName}
              onChange={handleChange}
              placeholder="Enter your full name"
              className={errors.teacherName ? "error" : ""}
            />
            {errors.teacherName && (
              <span className="error-message">{errors.teacherName}</span>
            )}
          </div>

          <div className="form-group">
            <label htmlFor="teacherId">Teacher ID</label>
            <input
              type="text"
              id="teacherId"
              name="teacherId"
              value={formData.teacherId}
              placeholder="Will be generated after registration"
              readOnly
              className="readonly-input"
            />
            <small className="helper-text">
              Your unique Teacher ID will be generated by the system after registration
            </small>
          </div>

          {message.text && (
            <div className={`message ${message.type}`}>{message.text}</div>
          )}

          <button
            type="submit"
            className="submit-btn"
            disabled={isSubmitting}
          >
            {isSubmitting ? "Registering..." : "Register"}
          </button>
        </form>
      </div>
    </div>
  );
};

export default TeacherSignup;
